spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1

server:
  port: 8001

eureka:
  instance:
    appname: spring-cloud-eureka
    hostname: peer1
    prefer-ip-address: false
  client:
    #表示是否将自己注册到Eureka Server
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息
    fetch-registry: true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl:
      #双节点模式配置
      #defaultZone: http://peer2:8002/eureka/
      #集群模式配置
      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/