spring:
  application:
    name: spring-cloud-config-server
  #Spring Cloud Config Server端配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wmmxsd/spring-cloud-demo
          search-paths: cloud-config
          username: GitHub账号
          password: GitHub密码
          default-label: master

    stream:
      default:
        producer:
          #解决kafka生产者发送消息报java.lang.IllegalArgumentException: Magic v1 does not support record headers错误
          headerMode: embeddedHeaders
        consumer:
          headerMode: embeddedHeaders
    bus:
      refresh:
        enabled: true

  kafka:
    bootstrap-servers: 192.168.119.25:9092   #配置 kafka 服务器的地址和端口
    consumer:
      group-id: Spring-Cloud-Bus
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#该应用端口号
server:
  port: 9051

#注册中心客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #以IP地址注册到服务中心
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）

management:
  endpoints:
    web:
      exposure:
        include: '*'   #refresh


