spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wmmxsd/spring-cloud-demo
          search-paths: cloud-config
          username: wmmxsd@126.com
          password: w7610232mm

server:
  port: 9051
