spring:
  application:
    name: spring-cloud-config-server
  #Spring Cloud Config Server端配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wmmxsd/spring-cloud-demo
          search-paths: cloud-config
          username: GitHub账号
          password: GitHub密码

#该应用端口号
server:
  port: 9051

#注册中心客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
