spring:
  application:
    name: node2
server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    #开启hystrix熔断器
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
