spring:
  application:
    name: spring-cloud-zuul
server:
  port: 9060
zuul:
  routes:
    producer:
      path: /producer/**
      serviceId: spring-cloud-producer
      #访问http://localhost:9060/producer/hello?name=2&token=1 返回hello 2，this is first message
    consumer:
      path: /consumer/**
      serviceId: spring-cloud-consumer
      #访问http://localhost:9060/consumer/helloWorld/2?token=1 返回hello 2，this is first message

